### PR TITLE
Fixed bandcamp track and album links

### PR DESCRIPTION
**Pull request by Walkyst**

### CODE REVIEW

**Comment by redbrain** [comment]
LGTM!

**Comment by aikaterna** [comment]
Thank you for doing this. This PR looks like it will close #526 , but I had one discrepancy while trying out this PR and testing it. When I load in https://deaddiskdrive.bandcamp.com/album/artificial-os, it misses track number 3 while gathering the songs (https://deaddiskdrive.bandcamp.com/track/3d-demo-disc). Other than this one issue I have not found anything else wrong with this PR and it looks good to go.

**Comment by MCOfficer** [comment]
Is there no error? the track is part of the extracted JSON, and nothing looks unusual about it.

<details>for reference, the JSON
<summary>For reference, this is the `trackinfo` section of JSON as found on the album website:</summary>

```
"trackinfo": [
    {
        "encoding_error": null,
        "is_downloadable": true,
        "license_type": 1,
        "file": {
            "mp3-128": "https://t4.bcbits.com/stream/4fa6df97c59f958d34466cc4c089fbf0/mp3-128/2658197655?p=0&amp;ts=1601489979&amp;t=247214d221d40d7e3b24d72e43903059bffa928c&amp;token=1601489979_6342229967bc23704b7e04b1b6db4e001c7cae3b"
        },
        "video_mobile_url": null,
        "album_preorder": false,
        "encoding_pending": null,
        "has_free_download": null,
        "video_poster_url": null,
        "unreleased_track": false,
        "title": "Installation Complete!",
        "track_id": 2658197655,
        "track_license_id": null,
        "play_count": null,
        "is_draft": false,
        "free_album_download": false,
        "encodings_id": 3348603493,
        "video_caption": null,
        "video_id": null,
        "duration": 12.8167,
        "title_link": "/track/installation-complete",
        "is_capped": null,
        "sizeof_lyrics": 0,
        "video_featured": null,
        "streaming": 1,
        "has_lyrics": false,
        "private": null,
        "video_source_type": null,
        "alt_link": null,
        "lyrics": null,
        "has_info": false,
        "id": 2658197655,
        "video_source_id": null,
        "track_num": 1
    },
    {
        "encoding_error": null,
        "is_downloadable": true,
        "license_type": 1,
        "file": {
            "mp3-128": "https://t4.bcbits.com/stream/006a7e10031148f170e5476683b99ac4/mp3-128/2296155045?p=0&amp;ts=1601489979&amp;t=eb864756e6015e7603670a56fdc883fe62617a8c&amp;token=1601489979_92df9c4d5756710c878938bd3438d4c2892ce8e9"
        },
        "video_mobile_url": null,
        "album_preorder": false,
        "encoding_pending": null,
        "has_free_download": null,
        "video_poster_url": null,
        "unreleased_track": false,
        "title": "Brand New OS",
        "track_id": 2296155045,
        "track_license_id": null,
        "play_count": null,
        "is_draft": false,
        "free_album_download": false,
        "encodings_id": 995673547,
        "video_caption": null,
        "video_id": null,
        "duration": 165.612,
        "title_link": "/track/brand-new-os",
        "is_capped": null,
        "sizeof_lyrics": 0,
        "video_featured": null,
        "streaming": 1,
        "has_lyrics": false,
        "private": null,
        "video_source_type": null,
        "alt_link": null,
        "lyrics": null,
        "has_info": false,
        "id": 2296155045,
        "video_source_id": null,
        "track_num": 2
    },
    {
        "encoding_error": null,
        "is_downloadable": true,
        "license_type": 1,
        "file": {
            "mp3-128": "https://t4.bcbits.com/stream/c7616731f751907267ab6c7b4882a5ce/mp3-128/3400146095?p=0&amp;ts=1601489979&amp;t=e20771ebbaee0a16ed308b2fc7b2c949b5c808d6&amp;token=1601489979_87a28715964a613232d494e11fb54e8c95e19afc"
        },
        "video_mobile_url": null,
        "album_preorder": false,
        "encoding_pending": null,
        "has_free_download": null,
        "video_poster_url": null,
        "unreleased_track": false,
        "title": "3D Demo Disc",
        "track_id": 3400146095,
        "track_license_id": null,
        "play_count": null,
        "is_draft": false,
        "free_album_download": false,
        "encodings_id": 984993413,
        "video_caption": null,
        "video_id": null,
        "duration": 170.266,
        "title_link": "/track/3d-demo-disc",
        "is_capped": null,
        "sizeof_lyrics": 0,
        "video_featured": null,
        "streaming": 1,
        "has_lyrics": false,
        "private": null,
        "video_source_type": null,
        "alt_link": null,
        "lyrics": null,
        "has_info": false,
        "id": 3400146095,
        "video_source_id": null,
        "track_num": 3
    },
    {
        "encoding_error": null,
        "is_downloadable": true,
        "license_type": 1,
        "file": {
            "mp3-128": "https://t4.bcbits.com/stream/597e4247af25f386a652ecb8a9fba6ca/mp3-128/280398431?p=0&amp;ts=1601489979&amp;t=7f0baccdf3dc0f519c89edd358b64a89f86cd053&amp;token=1601489979_2c28df20e5de5955289449a913faa5f3a1017154"
        },
        "video_mobile_url": null,
        "album_preorder": false,
        "encoding_pending": null,
        "has_free_download": null,
        "video_poster_url": null,
        "unreleased_track": false,
        "title": "Underwater Screensaver",
        "track_id": 280398431,
        "track_license_id": null,
        "play_count": null,
        "is_draft": false,
        "free_album_download": false,
        "encodings_id": 3353483984,
        "video_caption": null,
        "video_id": null,
        "duration": 145.608,
        "title_link": "/track/underwater-screensaver",
        "is_capped": null,
        "sizeof_lyrics": 0,
        "video_featured": null,
        "streaming": 1,
        "has_lyrics": false,
        "private": null,
        "video_source_type": null,
        "alt_link": null,
        "lyrics": null,
        "has_info": false,
        "id": 280398431,
        "video_source_id": null,
        "track_num": 4
    },
    {
        "encoding_error": null,
        "is_downloadable": true,
        "license_type": 1,
        "file": {
            "mp3-128": "https://t4.bcbits.com/stream/8de505c0ce2c631f3ba15a43fb8959e6/mp3-128/1845346583?p=0&amp;ts=1601489979&amp;t=d9ed8030215c8fb482f6e2f336d2aa0c9230f8e8&amp;token=1601489979_2b6bd0c7c03832d5ae7bc1eae7f952124a07570b"
        },
        "video_mobile_url": null,
        "album_preorder": false,
        "encoding_pending": null,
        "has_free_download": null,
        "video_poster_url": null,
        "unreleased_track": false,
        "title": "Animated Cursor Set",
        "track_id": 1845346583,
        "track_license_id": null,
        "play_count": null,
        "is_draft": false,
        "free_album_download": false,
        "encodings_id": 1680934200,
        "video_caption": null,
        "video_id": null,
        "duration": 164.005,
        "title_link": "/track/animated-cursor-set",
        "is_capped": null,
        "sizeof_lyrics": 0,
        "video_featured": null,
        "streaming": 1,
        "has_lyrics": false,
        "private": null,
        "video_source_type": null,
        "alt_link": null,
        "lyrics": null,
        "has_info": false,
        "id": 1845346583,
        "video_source_id": null,
        "track_num": 5
    },
    {
        "encoding_error": null,
        "is_downloadable": true,
        "license_type": 1,
        "file": {
            "mp3-128": "https://t4.bcbits.com/stream/2054a0ede07261bfb61f8788c74d7bb0/mp3-128/1681310860?p=0&amp;ts=1601489979&amp;t=024c944e0fbf8bf6ac0bd5891e0a5a86abfa3249&amp;token=1601489979_1b82fa943ddf8cc00ba4c272bceb7085deb97de6"
        },
        "video_mobile_url": null,
        "album_preorder": false,
        "encoding_pending": null,
        "has_free_download": null,
        "video_poster_url": null,
        "unreleased_track": false,
        "title": "Vanity Programs",
        "track_id": 1681310860,
        "track_license_id": null,
        "play_count": null,
        "is_draft": false,
        "free_album_download": false,
        "encodings_id": 2888460000,
        "video_caption": null,
        "video_id": null,
        "duration": 145.737,
        "title_link": "/track/vanity-programs",
        "is_capped": null,
        "sizeof_lyrics": 0,
        "video_featured": null,
        "streaming": 1,
        "has_lyrics": false,
        "private": null,
        "video_source_type": null,
        "alt_link": null,
        "lyrics": null,
        "has_info": false,
        "id": 1681310860,
        "video_source_id": null,
        "track_num": 6
    },
    {
        "encoding_error": null,
        "is_downloadable": true,
        "license_type": 1,
        "file": {
            "mp3-128": "https://t4.bcbits.com/stream/d928d0e5e3e8e530ea5a90767993e820/mp3-128/582878897?p=0&amp;ts=1601489979&amp;t=e0cd6ca7d531c1e48addfbf3c00286789a1da872&amp;token=1601489979_d7389cca747b925fcdc1f03c9295c0eaa09b7429"
        },
        "video_mobile_url": null,
        "album_preorder": false,
        "encoding_pending": null,
        "has_free_download": null,
        "video_poster_url": null,
        "unreleased_track": false,
        "title": "Connected to the Chatroom! (feat. Mac Bandit)",
        "track_id": 582878897,
        "track_license_id": null,
        "play_count": null,
        "is_draft": false,
        "free_album_download": false,
        "encodings_id": 3598462659,
        "video_caption": null,
        "video_id": null,
        "duration": 271.312,
        "title_link": "/track/connected-to-the-chatroom-feat-mac-bandit",
        "is_capped": null,
        "sizeof_lyrics": 0,
        "video_featured": null,
        "streaming": 1,
        "has_lyrics": false,
        "private": null,
        "video_source_type": null,
        "alt_link": null,
        "lyrics": null,
        "has_info": true,
        "id": 582878897,
        "video_source_id": null,
        "track_num": 7
    },
    {
        "encoding_error": null,
        "is_downloadable": true,
        "license_type": 1,
        "file": {
            "mp3-128": "https://t4.bcbits.com/stream/e54a801172cc1228dee3195cca998211/mp3-128/2965490929?p=0&amp;ts=1601489979&amp;t=cdc9e5c126d039ed1a65e34be7d3ff235570bbef&amp;token=1601489979_380dcf41cd860c4d239d570680bfcadd762a6ac6"
        },
        "video_mobile_url": null,
        "album_preorder": false,
        "encoding_pending": null,
        "has_free_download": null,
        "video_poster_url": null,
        "unreleased_track": false,
        "title": "Online Shopping Experience",
        "track_id": 2965490929,
        "track_license_id": null,
        "play_count": null,
        "is_draft": false,
        "free_album_download": false,
        "encodings_id": 2909882274,
        "video_caption": null,
        "video_id": null,
        "duration": 129.49,
        "title_link": "/track/online-shopping-experience",
        "is_capped": null,
        "sizeof_lyrics": 0,
        "video_featured": null,
        "streaming": 1,
        "has_lyrics": false,
        "private": null,
        "video_source_type": null,
        "alt_link": null,
        "lyrics": null,
        "has_info": false,
        "id": 2965490929,
        "video_source_id": null,
        "track_num": 8
    },
    {
        "encoding_error": null,
        "is_downloadable": true,
        "license_type": 1,
        "file": {
            "mp3-128": "https://t4.bcbits.com/stream/47faf9a1c74506c02a20d92d47bda228/mp3-128/910396513?p=0&amp;ts=1601489979&amp;t=46118acdbea4a713611a227d1edc6b69047e3773&amp;token=1601489979_1b596b8fc67d833f38458bcd25c50fe679460126"
        },
        "video_mobile_url": null,
        "album_preorder": false,
        "encoding_pending": null,
        "has_free_download": null,
        "video_poster_url": null,
        "unreleased_track": false,
        "title": "Finding Folders...",
        "track_id": 910396513,
        "track_license_id": null,
        "play_count": null,
        "is_draft": false,
        "free_album_download": false,
        "encodings_id": 3450770998,
        "video_caption": null,
        "video_id": null,
        "duration": 124.142,
        "title_link": "/track/finding-folders",
        "is_capped": null,
        "sizeof_lyrics": 0,
        "video_featured": null,
        "streaming": 1,
        "has_lyrics": false,
        "private": null,
        "video_source_type": null,
        "alt_link": null,
        "lyrics": null,
        "has_info": false,
        "id": 910396513,
        "video_source_id": null,
        "track_num": 9
    },
    {
        "encoding_error": null,
        "is_downloadable": true,
        "license_type": 1,
        "file": {
            "mp3-128": "https://t4.bcbits.com/stream/f83b52c5bf16c68f2d0f5341916bd787/mp3-128/1212054135?p=0&amp;ts=1601489979&amp;t=983155998b35b6b075fd53e34e680200fc082f52&amp;token=1601489979_ade40f866541ff601426b4e86835af1684256ee6"
        },
        "video_mobile_url": null,
        "album_preorder": false,
        "encoding_pending": null,
        "has_free_download": null,
        "video_poster_url": null,
        "unreleased_track": false,
        "title": "Through the World Wide Web",
        "track_id": 1212054135,
        "track_license_id": null,
        "play_count": null,
        "is_draft": false,
        "free_album_download": false,
        "encodings_id": 4283530537,
        "video_caption": null,
        "video_id": null,
        "duration": 142.743,
        "title_link": "/track/through-the-world-wide-web",
        "is_capped": null,
        "sizeof_lyrics": 0,
        "video_featured": null,
        "streaming": 1,
        "has_lyrics": false,
        "private": null,
        "video_source_type": null,
        "alt_link": null,
        "lyrics": null,
        "has_info": false,
        "id": 1212054135,
        "video_source_id": null,
        "track_num": 10
    },
    {
        "encoding_error": null,
        "is_downloadable": true,
        "license_type": 1,
        "file": {
            "mp3-128": "https://t4.bcbits.com/stream/55671664de0453c8c36df95c77847d03/mp3-128/2798771237?p=0&amp;ts=1601489979&amp;t=e9e8affb96fc7b492b12f9bece632dc2e185e2e1&amp;token=1601489979_16a5d47dbd0b5f5556d4949ba76af730318eefe5"
        },
        "video_mobile_url": null,
        "album_preorder": false,
        "encoding_pending": null,
        "has_free_download": null,
        "video_poster_url": null,
        "unreleased_track": false,
        "title": "Shattered Macintosh Dreams",
        "track_id": 2798771237,
        "track_license_id": null,
        "play_count": null,
        "is_draft": false,
        "free_album_download": false,
        "encodings_id": 2248135080,
        "video_caption": null,
        "video_id": null,
        "duration": 133.418,
        "title_link": "/track/shattered-macintosh-dreams",
        "is_capped": null,
        "sizeof_lyrics": 0,
        "video_featured": null,
        "streaming": 1,
        "has_lyrics": false,
        "private": null,
        "video_source_type": null,
        "alt_link": null,
        "lyrics": null,
        "has_info": false,
        "id": 2798771237,
        "video_source_id": null,
        "track_num": 11
    }
],
```

</details>

**Comment by aikaterna** [comment]
There were no errors. The Discord embed indicated 12 songs and 11 were picked up by the bot. Would be interested to know if anyone else can repro this with this album link.

```
2020-09-29 19:48:03.181  INFO 4908 --- [  XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://deaddiskdrive.bandcamp.com/album/artificial-os"
2020-09-29 19:48:03.212  INFO 4908 --- [   XNIO-1 I/O-1] lavalink.server.io.SocketServer          : {"op": "voiceUpdate", "guildId": “redacted”, "sessionId": "redacted", "event": {"token": "redacted", "guild_id": "redacted", "endpoint": "us-east6.discord.media:443"}}
2020-09-29 19:48:04.416  INFO 4908 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Artificial OS
2020-09-29 19:48:04.494  INFO 4908 --- [   XNIO-1 I/O-1] lavalink.server.io.SocketServer          : {"op": "play", "guildId": "redacted", "track": "QAAAugIAD1Zhbml0eSBQcm9ncmFtcwAWQ29ycnVwdGVkIERhdGEgQ29ycOKEogAAAAAAAjlJADhodHRwczovL2RlYWRkaXNrZHJpdmUuYmFuZGNhbXAuY29tL3RyYWNrL3Zhbml0eS1wcm9ncmFtcwABADhodHRwczovL2RlYWRkaXNrZHJpdmUuYmFuZGNhbXAuY29tL3RyYWNrL3Zhbml0eS1wcm9ncmFtcwAIYmFuZGNhbXAAAAAAAAAAAA=="}
```
image

**Comment by Walkyst** [comment]
I think it is issue with bandcamp itself, because in this album total 11 songs, just compare what tracks in your bot queue and what tracks has on album

> There were no errors. The Discord embed indicated 12 songs and 11 were picked up by the bot. Would be interested to know if anyone else can repro this with this album link.
> 
> Edit: I'm a Lavalink user but I'm using Devoxin's Lavaplayer fork @ 1.3.53 with this fix applied on top.
> 
> ```
> 2020-09-29 19:48:03.181  INFO 4908 --- [  XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://deaddiskdrive.bandcamp.com/album/artificial-os"
> 2020-09-29 19:48:03.212  INFO 4908 --- [   XNIO-1 I/O-1] lavalink.server.io.SocketServer          : {"op": "voiceUpdate", "guildId": “redacted”, "sessionId": "redacted", "event": {"token": "redacted", "guild_id": "redacted", "endpoint": "us-east6.discord.media:443"}}
> 2020-09-29 19:48:04.416  INFO 4908 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Artificial OS
> 2020-09-29 19:48:04.494  INFO 4908 --- [   XNIO-1 I/O-1] lavalink.server.io.SocketServer          : {"op": "play", "guildId": "redacted", "track": "QAAAugIAD1Zhbml0eSBQcm9ncmFtcwAWQ29ycnVwdGVkIERhdGEgQ29ycOKEogAAAAAAAjlJADhodHRwczovL2RlYWRkaXNrZHJpdmUuYmFuZGNhbXAuY29tL3RyYWNrL3Zhbml0eS1wcm9ncmFtcwABADhodHRwczovL2RlYWRkaXNrZHJpdmUuYmFuZGNhbXAuY29tL3RyYWNrL3Zhbml0eS1wcm9ncmFtcwAIYmFuZGNhbXAAAAAAAAAAAA=="}
> ```
> 
> image

**Comment by JDCourtney1969** [comment]
Hi.  I'm just a spectator here - a heavy user of Bandcamp who has used a couple of programs and web sites to convert many Bandcamp tracks to WAV files.   As of about a week ago, I am no longer able to produce large WAV files.   Someone told me it has something to do with "youtube-dl"...?  I am guessing it's a result of some changes made by people at Bandcamp....?     Is anyone else aware of this and has anyone tried to address this?   Either here, or in a different place (pull request?) on this site?   I am very new to this site and am having trouble navigating.  I'm just desperate to get this issue resolved.   Can anyone please help, or tell me where to go to find help?    Thank you!

**Comment by Walkyst** [comment]
@JDCourtney1969 You can try this https://github.com/Otiel/BandcampDownloader and if you have any issues with their program create issue in their repository

**Comment by JDCourtney1969** [comment]
> @JDCourtney1969 You can try this https://github.com/Otiel/BandcampDownloader and if you have any issues with their program create issue in their repository



> @JDCourtney1969 You can try this https://github.com/Otiel/BandcampDownloader and if you have any issues with their program create issue in their repository

Thanks so much for the link!  However, my excitement was dashed when I learned that this is a Windows application.  I have a MacBook Pro laptop.....

**Pull request merged**
