### PR TITLE
Allow livestreams in search results.

### PR DESCRIPTION
**Pull request by HeadTriXz**
No idea if what I did would work since I never used Java before and didn't test or check it. Either way, I would like it if live streams weren't filtered out.

### CODE REVIEW

**Comment by MCOfficer** [comment]
Refs #107

**Comment by HeadTriXz** [comment]
Hmm yes, doesn't work. But still, live streams not being filtered out would still be appreciated.

**Comment by sedmelluq** [comment]
Would only be acceptable if this were an option that can be enabled.

**Comment by HeadTriXz** [comment]
> Would only be acceptable if this were an option that can be enabled.

Wouldn't hurt to add the option

**Pull request closed without merging**
