### PR TITLE
Updated twitch API url

### PR DESCRIPTION
**Pull request by Thewsomeguy**
The current URL seems to be giving a 404. I don't know much about Java, but looking at the response the URL should work.

### CODE REVIEW

**Comment by MCOfficer** [comment]
kraken is the APIv5, the new api is `helix`. for support beyond 2018, one should switch to that, but switching might break some stuff in the process.

**Comment by Thewsomeguy** [comment]
That endpoint does return an empty array if not found, yes. It returns the stream status, but it doesn't return the streamer's display name, which is used for the Track author.

**Comment by mittalyashu** [comment]
Any progress?

**Comment by MCOfficer** [comment]
should be closed in favour of #132 or something else, as kraken will close in 2 months

**Comment by sedmelluq** [comment]
Helix version merged instead.

**Pull request closed without merging**
