### PR TITLE
Requesting PLAYER_JS_URL from other place if other fail

### LINKED ISSUE #597: missing PLAYER_JS_URL
hey, a few days ago i got this error when trying to load a track. however, i got it once in like 20+ times, so i guess it's not easily reproducible.

i was running version 1.3.72, and i don't think 1.3.73 would fix it.

log: https://mlnr.dev/up/log.log (it's too long for haste services)

### PR DESCRIPTION
**Pull request by Walkyst**
This should fix #597

### CODE REVIEW

**Comment by llacb47** [comment]
This is not a fix, then `ytInitialData` will throw the error instead. You need to add the cookie header to bypass the consent redirect.

**Comment by PredaaA** [comment]
I tried the PR and can confirm that it fixes it.

**Review by Favna — APPROVED** [review]

**Comment by markozajc** [comment]
There's a far easier fix: https://github.com/iv-org/invidious/issues/1959#issuecomment-811463524

**Comment by Walkyst** [comment]
Nice found with that cookie, but I'm not sure is that reliable fix for long time

**Comment by markozajc** [comment]
That's what most downloaders did to fix it. I guess only time will tell whether or not it's reliable.

**Pull request closed without merging**
