### PR TITLE
Support for searching on YouTube Music

### PR DESCRIPTION
**Pull request by Walkyst**
This maybe can be done in more good way but my knowledge of Java is not the best

Overall this PR implementing ability to search music videos on YouTube Music through `ytmsearch:`, can be very useful for those who converting Spotify playlists to YouTube one

About `YT_MUSIC_KEY` seems like this key is constant and not changing, but if something go wrong this key can be obtain on music.youtube.com or youtube.com from `INNERTUBE_API_KEY` field

### CODE REVIEW

**Comment by duncte123** [comment]
visiting youtube music myself gives me a different API key, maybe it is better to load the key on boot of the music manager in case it is region locked

**Comment by Walkyst** [comment]
> visiting youtube music myself gives me a different API key, maybe it is better to load the key on boot of the music manager in case it is region locked

Maybe yes, but when I try do Get request YouTube Music just send that it not supported on this browser, so I see only way get it from default YouTube but in that case we need do one more request.

Anyway if you get different YT Music key, can you try this code with current key, so we can know if it work or no

**Comment by duncte123** [comment]
Actually nvm, there seem to be two `INNERTUBE_API_KEY` fields, one in lowercase.
I still think that it's a good idea to fetch the key at startup just in case it ever changes in the future

**Comment by sedmelluq** [comment]
There is practically no shared code between this and the normal search, so it would make more sense to put it into its own class.

**Comment by Walkyst** [comment]
Hm, not sure if it right but then i need create `YoutubeSearchMusicResultLoader` interface for that or it can be done in other way?

**Comment by sedmelluq** [comment]
Indeed, create `YoutubeSearchMusicResultLoader` and `DefaultYoutubeSearchMusicResultLoader`.

**Comment by deebah** [comment]
This seems like a good idea, will it ever be merged?

**Pull request merged**
